/* 자동 생성: scripts/import_art.py — 손으로 고치지 마세요 */
window.OKS_ART = {
"ready": [
"art/obj/potato.webp",
"art/obj/sweet_potato.webp",
"art/obj/corn.webp",
"art/obj/cucumber.webp",
"art/obj/onion.webp",
"art/obj/cabbage.webp",
"art/obj/pumpkin.webp",
"art/obj/mushroom.webp",
"art/obj/pepper.webp",
"art/obj/alarm.webp",
"art/obj/smartphone.webp",
"art/obj/telephone.webp",
"art/obj/key.webp",
"art/obj/umbrella.webp",
"art/obj/toothbrush.webp",
"art/obj/soap.webp",
"art/obj/towel.webp",
"art/obj/spoon.webp",
"art/obj/chair.webp",
"art/obj/bed.webp",
"art/obj/tv.webp",
"art/obj/fridge.webp",
"art/obj/fan.webp",
"art/obj/bulb.webp",
"art/obj/flashlight.webp",
"art/obj/trash_can.webp",
"art/obj/eco_bag.webp",
"art/obj/car.webp",
"art/obj/bus.webp",
"art/obj/taxi.webp",
"art/obj/ambulance.webp",
"art/obj/firetruck.webp",
"art/obj/policecar.webp",
"art/obj/bicycle.webp",
"art/obj/train.webp",
"art/obj/airplane.webp",
"art/obj/boat.webp",
"art/obj/subway.webp",
"art/obj/truck.webp",
"art/obj/motorbike.webp",
"art/obj/kickboard.webp",
"art/obj/helicopter.webp",
"art/obj/excavator.webp",
"art/obj/wheelchair.webp",
"art/obj/elevator.webp",
"art/obj/pl_school.webp",
"art/obj/pl_hospital.webp",
"art/obj/pl_bank.webp",
"art/obj/pl_post.webp",
"art/obj/pl_police.webp",
"art/obj/pl_fire.webp",
"art/obj/pl_mart.webp",
"art/obj/pl_library.webp",
"art/obj/pl_park.webp",
"art/obj/pl_pharmacy.webp",
"art/obj/pl_busstop.webp",
"art/obj/pl_station.webp",
"art/obj/pl_toilet.webp",
"art/obj/pl_cafeteria.webp",
"art/obj/pl_center.webp",
"art/obj/pl_cinema.webp",
"art/obj/pl_home.webp",
"art/obj/pl_ground.webp",
"art/obj/drum.webp",
"art/obj/xylophone.webp",
"art/obj/piano.webp",
"art/obj/tambourine.webp",
"art/obj/triangle.webp",
"art/obj/recorder.webp",
"art/obj/guitar.webp",
"art/obj/maracas.webp",
"art/obj/janggu.webp",
"art/obj/sogo.webp",
"art/obj/kkwaenggwari.webp",
"art/obj/jing.webp",
"art/obj/castanets.webp",
"art/obj/violin.webp",
"art/obj/trumpet.webp",
"art/obj/bell.webp",
"art/obj/danso.webp",
"art/obj/headphones.webp",
"art/obj/brush.webp",
"art/obj/palette.webp",
"art/obj/watercolor.webp",
"art/obj/clay.webp",
"art/obj/easel.webp",
"art/obj/sketchbook.webp",
"art/obj/inkstone.webp",
"art/obj/water_jar.webp",
"art/obj/colored_pencil.webp",
"art/obj/magnifier.webp",
"art/obj/thermometer.webp",
"art/obj/scale.webp",
"art/obj/magnet.webp",
"art/obj/beaker.webp",
"art/obj/dropper.webp",
"art/obj/microscope.webp",
"art/obj/compass.webp",
"art/obj/battery_bulb.webp",
"art/obj/tape_measure.webp",
"art/obj/protractor.webp",
"art/obj/hourglass.webp",
"art/obj/measuring_cup.webp",
"art/obj/measuring_spoon.webp",
"art/obj/stopwatch.webp",
"art/obj/prism.webp",
"art/obj/mirror.webp",
"art/obj/bathroom_scale.webp",
"art/obj/sun.webp",
"art/obj/cloud.webp",
"art/obj/rain.webp",
"art/obj/snow.webp",
"art/obj/rainbow.webp",
"art/obj/wind.webp",
"art/obj/moon_night.webp",
"art/obj/star.webp",
"art/obj/lightning.webp",
"art/obj/tree.webp",
"art/obj/flower.webp",
"art/obj/grass.webp",
"art/obj/rock.webp",
"art/obj/mountain.webp",
"art/obj/river.webp",
"art/obj/wave.webp",
"art/obj/fire.webp",
"art/obj/leaf.webp",
"art/obj/fish.webp",
"art/obj/turtle.webp",
"art/obj/bird.webp",
"art/obj/eagle.webp",
"art/obj/butterfly.webp",
"art/obj/chicken.webp",
"art/obj/cow.webp",
"art/obj/pig.webp",
"art/obj/duck.webp",
"art/obj/sheep.webp",
"art/obj/horse.webp",
"art/obj/squirrel.webp",
"art/obj/whale.webp",
"art/obj/dolphin.webp",
"art/obj/crab.webp",
"art/obj/octopus.webp",
"art/obj/ant.webp",
"art/obj/snail.webp",
"art/act/feel_happy.webp",
"art/act/feel_sad.webp",
"art/act/feel_angry.webp",
"art/act/feel_scared.webp",
"art/act/feel_surprised.webp",
"art/act/feel_calm.webp",
"art/act/feel_tired.webp",
"art/act/feel_sick.webp",
"art/act/feel_proud.webp",
"art/act/do_brush.webp",
"art/act/do_shoes.webp",
"art/act/do_eat.webp",
"art/act/do_pour.webp",
"art/act/do_pay.webp",
"art/act/do_card.webp",
"art/act/do_call.webp",
"art/act/do_pack.webp",
"art/act/do_sleep.webp",
"art/people/p_cashier.webp",
"art/people/p_barista.webp",
"art/people/p_baker.webp",
"art/people/p_farmer.webp",
"art/people/p_delivery.webp",
"art/people/p_driver.webp",
"art/people/p_cleaner.webp",
"art/people/p_banker.webp",
"art/people/p_postman.webp",
"art/people/p_mom.webp",
"art/people/p_dad.webp",
"art/people/p_grandma.webp",
"art/people/p_grandpa.webp",
"art/people/p_baby.webp",
"art/people/p_sister.webp",
"art/people/p_brother.webp",
"art/people/p_friend_boy.webp",
"art/people/p_neighbor.webp",
"art/space/space_bg.webp",
"art/space/space_bg_tall.webp",
"art/space/star_center.webp",
"art/space/star_sea.webp",
"art/space/star_love.webp",
"art/space/star_dream.webp",
"art/space/star_farm.webp",
"art/space/star_jungle.webp",
"art/space/star_word.webp",
"art/space/egg_sleep.webp",
"art/space/egg_crack.webp",
"art/space/egg_born.webp",
"art/space/ship.webp",
"art/space/ship_fly.webp",
"art/space/comet.webp",
"art/space/ring_planet.webp",
"art/space/moon.webp",
"art/space/satellite.webp",
"art/space/shooting_star.webp",
"art/space/galaxy.webp",
"art/space/asteroid.webp",
"art/space/space_cloud.webp",
"art/space/telescope.webp",
"art/build/b_hall.webp",
"art/build/b_library.webp",
"art/build/b_post.webp",
"art/build/b_broadcast.webp",
"art/build/b_english.webp",
"art/build/b_adventure.webp",
"art/build/b_myroom.webp",
"art/build/b_dock.webp",
"art/build/b_music_hall.webp",
"art/build/b_rhythm_stage.webp",
"art/build/b_gugak.webp",
"art/build/b_color_studio.webp",
"art/build/b_sculpt.webp",
"art/build/b_gallery.webp",
"art/build/b_bakery.webp",
"art/build/b_mart.webp",
"art/build/b_block_factory.webp",
"art/build/b_lab.webp",
"art/build/b_observatory.webp",
"art/build/b_greenhouse.webp",
"art/build/b_explorer.webp",
"art/build/b_transit.webp",
"art/build/b_safety.webp",
"art/build/b_museum.webp",
"art/build/b_job_center.webp",
"art/build/b_shop_street.webp",
"art/build/b_farm.webp",
"art/char/ok_wave.webp",
"art/char/ok_think.webp",
"art/char/ok_clap.webp",
"art/char/ok_comfort.webp",
"art/char/ok_space.webp",
"art/char/robot_wave.webp",
"art/char/robot_point.webp",
"art/char/robot_cheer.webp",
"art/char/sea_wave.webp",
"art/char/sea_point.webp",
"art/char/sea_cheer.webp",
"art/char/love_wave.webp",
"art/char/love_point.webp",
"art/char/love_cheer.webp",
"art/char/dream_wave.webp",
"art/char/dream_point.webp",
"art/char/dream_cheer.webp",
"art/space/land_center.webp",
"art/space/land_sea.webp",
"art/space/land_love.webp",
"art/space/land_dream.webp",
"art/space/land_farm.webp",
"art/avatar/kid_boy1.webp",
"art/avatar/kid_girl1.webp",
"art/avatar/kid_boy2.webp",
"art/avatar/kid_girl2.webp",
"art/avatar/kid_boy1_space.webp",
"art/avatar/kid_girl1_space.webp",
"art/avatar/kid_boy2_space.webp",
"art/avatar/kid_girl2_space.webp",
"art/avatar/teen_boy1.webp",
"art/avatar/teen_girl1.webp",
"art/avatar/teen_boy2.webp",
"art/avatar/teen_girl2.webp",
"art/avatar/teen_boy1_space.webp",
"art/avatar/teen_girl1_space.webp",
"art/avatar/teen_boy2_space.webp",
"art/avatar/teen_girl2_space.webp"
],
"icons": {
"🥔": "art/obj/potato.webp",
"🍠": "art/obj/sweet_potato.webp",
"🌽": "art/obj/corn.webp",
"🥒": "art/obj/cucumber.webp",
"🧅": "art/obj/onion.webp",
"🥬": "art/obj/cabbage.webp",
"🎃": "art/obj/pumpkin.webp",
"🍄": "art/obj/mushroom.webp",
"🌶️": "art/obj/pepper.webp",
"⏰": "art/obj/alarm.webp",
"📱": "art/obj/smartphone.webp",
"☎️": "art/obj/telephone.webp",
"🔑": "art/obj/key.webp",
"☂️": "art/obj/umbrella.webp",
"🪥": "art/obj/toothbrush.webp",
"🧼": "art/obj/soap.webp",
"🥄": "art/obj/spoon.webp",
"🪑": "art/obj/chair.webp",
"🛌": "art/obj/bed.webp",
"🛏️": "art/obj/bed.webp",
"📺": "art/obj/tv.webp",
"🧊": "art/obj/fridge.webp",
"🌀": "art/obj/fan.webp",
"💡": "art/obj/bulb.webp",
"🔦": "art/obj/flashlight.webp",
"🗑️": "art/obj/trash_can.webp",
"🛍️": "art/obj/eco_bag.webp",
"🚗": "art/obj/car.webp",
"🚌": "art/obj/bus.webp",
"🚕": "art/obj/taxi.webp",
"🚑": "art/obj/ambulance.webp",
"🚒": "art/obj/firetruck.webp",
"🚓": "art/obj/policecar.webp",
"🚲": "art/obj/bicycle.webp",
"🚂": "art/obj/train.webp",
"🚉": "art/obj/train.webp",
"🚃": "art/obj/train.webp",
"✈️": "art/obj/airplane.webp",
"⛵": "art/obj/boat.webp",
"🚢": "art/obj/boat.webp",
"🚇": "art/obj/subway.webp",
"🚚": "art/obj/truck.webp",
"🛵": "art/obj/motorbike.webp",
"🛴": "art/obj/kickboard.webp",
"🚁": "art/obj/helicopter.webp",
"🚜": "art/obj/excavator.webp",
"♿": "art/obj/wheelchair.webp",
"🛗": "art/obj/elevator.webp",
"🏫": "art/obj/pl_school.webp",
"🏥": "art/obj/pl_hospital.webp",
"🏦": "art/obj/pl_bank.webp",
"📮": "art/obj/pl_post.webp",
"🚔": "art/obj/pl_police.webp",
"🛒": "art/obj/pl_mart.webp",
"📚": "art/obj/pl_library.webp",
"🌳": "art/obj/pl_park.webp",
"🏞️": "art/obj/pl_park.webp",
"💊": "art/obj/pl_pharmacy.webp",
"🚏": "art/obj/pl_busstop.webp",
"🚻": "art/obj/pl_toilet.webp",
"🍱": "art/obj/pl_cafeteria.webp",
"🏛️": "art/obj/pl_center.webp",
"🎬": "art/obj/pl_cinema.webp",
"🏠": "art/obj/pl_home.webp",
"⚽": "art/obj/pl_ground.webp",
"🥁": "art/obj/drum.webp",
"🎼": "art/obj/xylophone.webp",
"🎹": "art/obj/piano.webp",
"🔔": "art/obj/tambourine.webp",
"🔺": "art/obj/triangle.webp",
"🎸": "art/obj/guitar.webp",
"🎻": "art/obj/violin.webp",
"🎺": "art/obj/trumpet.webp",
"🎧": "art/obj/headphones.webp",
"🖌️": "art/obj/brush.webp",
"🎨": "art/obj/palette.webp",
"🖼️": "art/obj/easel.webp",
"🔎": "art/obj/magnifier.webp",
"🔍": "art/obj/magnifier.webp",
"🌡️": "art/obj/thermometer.webp",
"⚖️": "art/obj/scale.webp",
"🧲": "art/obj/magnet.webp",
"🧪": "art/obj/beaker.webp",
"🔬": "art/obj/microscope.webp",
"🧭": "art/obj/compass.webp",
"🔋": "art/obj/battery_bulb.webp",
"📐": "art/obj/tape_measure.webp",
"⏳": "art/obj/hourglass.webp",
"⌛": "art/obj/hourglass.webp",
"⏱️": "art/obj/stopwatch.webp",
"🪞": "art/obj/mirror.webp",
"☀️": "art/obj/sun.webp",
"☁️": "art/obj/cloud.webp",
"🌧️": "art/obj/rain.webp",
"❄️": "art/obj/snow.webp",
"🌈": "art/obj/rainbow.webp",
"💨": "art/obj/wind.webp",
"🌬️": "art/obj/wind.webp",
"🌙": "art/obj/moon_night.webp",
"⭐": "art/obj/star.webp",
"⚡": "art/obj/lightning.webp",
"🌸": "art/obj/flower.webp",
"🌷": "art/obj/flower.webp",
"🌿": "art/obj/grass.webp",
"🪨": "art/obj/rock.webp",
"⛰️": "art/obj/mountain.webp",
"🌊": "art/obj/wave.webp",
"🔥": "art/obj/fire.webp",
"🍂": "art/obj/leaf.webp",
"🐟": "art/obj/fish.webp",
"🐢": "art/obj/turtle.webp",
"🐦": "art/obj/bird.webp",
"🦅": "art/obj/eagle.webp",
"🦋": "art/obj/butterfly.webp",
"🐔": "art/obj/chicken.webp",
"🐄": "art/obj/cow.webp",
"🐷": "art/obj/pig.webp",
"🦆": "art/obj/duck.webp",
"🐑": "art/obj/sheep.webp",
"🐴": "art/obj/horse.webp",
"🐿️": "art/obj/squirrel.webp",
"🐳": "art/obj/whale.webp",
"🐬": "art/obj/dolphin.webp",
"🦀": "art/obj/crab.webp",
"🐙": "art/obj/octopus.webp",
"🐜": "art/obj/ant.webp",
"🐌": "art/obj/snail.webp",
"😊": "art/act/feel_happy.webp",
"😆": "art/act/feel_happy.webp",
"😄": "art/act/feel_happy.webp",
"😢": "art/act/feel_sad.webp",
"😭": "art/act/feel_sad.webp",
"😠": "art/act/feel_angry.webp",
"😡": "art/act/feel_angry.webp",
"😤": "art/act/feel_angry.webp",
"😨": "art/act/feel_scared.webp",
"😲": "art/act/feel_surprised.webp",
"😌": "art/act/feel_calm.webp",
"😴": "art/act/feel_tired.webp",
"💤": "art/act/feel_tired.webp",
"🤒": "art/act/feel_sick.webp",
"💪": "art/act/feel_proud.webp",
"👟": "art/act/do_shoes.webp",
"🍚": "art/act/do_eat.webp",
"😋": "art/act/do_eat.webp",
"💧": "art/act/do_pour.webp",
"💵": "art/act/do_pay.webp",
"💳": "art/act/do_card.webp",
"📞": "art/act/do_call.webp",
"🎒": "art/act/do_pack.webp",
"☕": "art/people/p_barista.webp",
"🍞": "art/people/p_baker.webp",
"🌾": "art/people/p_farmer.webp",
"📦": "art/people/p_delivery.webp",
"🧹": "art/people/p_cleaner.webp",
"👩": "art/people/p_mom.webp",
"👨": "art/people/p_dad.webp",
"👵": "art/people/p_grandma.webp",
"👴": "art/people/p_grandpa.webp",
"👶": "art/people/p_baby.webp",
"👧": "art/people/p_sister.webp",
"👦": "art/people/p_brother.webp",
"🧒": "art/people/p_friend_boy.webp",
"🙋": "art/people/p_neighbor.webp"
}
};
