/* 햇살 농장 v8 — real individual user's sprites, fixed 1672×941 design coordinates.
 * The full stage scales as one unit, retaining the approved composition at every viewport.
 * Saved legacy farm data is copied once; original save key is never overwritten.
 */
(()=>{'use strict';
const $=id=>document.getElementById(id),A='assets/',SAVE='oks_farm_scene_v8',LEGACY='oks_math_tycoon_v1';
const CROPS={tomato:{name:'토마토',price:4,icon:'harvest_tomato',plant:'tomato_plant',growth:'young_plant'},strawberry:{name:'딸기',price:3,icon:'harvest_strawberry',plant:'strawberry_plant',growth:'young_plant'},lettuce:{name:'상추',price:4,icon:'harvest_lettuce',plant:'lettuce_plant',growth:'young_plant'},carrot:{name:'당근',price:5,icon:'harvest_carrot',plant:'carrot_cluster',growth:'young_plant'}};
const DEMO_ORDERS=[{guest:'cat',ask:{tomato:3,lettuce:1}},{guest:'panda',ask:{tomato:2,lettuce:1}},{guest:'monkey',ask:{carrot:2,lettuce:2}},{guest:'cat',ask:{strawberry:2,lettuce:1}},{guest:'panda',ask:{strawberry:3}},{guest:'monkey',ask:{carrot:3,tomato:1}}];
const asset=(name)=>A+name+'.webp';let live,action='harvest',voice=true,noticeTimer=0;
const newState=()=>({coins:0,stars:0,served:0,day:1,plots:[{phase:'ready',crop:'tomato'},{phase:'ready',crop:'strawberry'},{phase:'seeded',crop:'lettuce'},{phase:'ready',crop:'lettuce'},{phase:'empty',crop:null},{phase:'empty',crop:null}],stock:{tomato:0,strawberry:0,lettuce:0,carrot:0},tray:[],selected:'tomato',customer:0,unlocked:6,mode:'guided',tutorial:true});
function load(){let state=newState();try{const old=JSON.parse(localStorage.getItem(LEGACY)||'null');if(old&&Number.isFinite(old.coins)){state.coins=Math.max(0,old.coins);state.stars=Math.max(0,old.stars||0);state.served=Math.max(0,old.served||0);state.day=Math.max(1,old.day||1);/* A fresh scenic greenhouse starts with playable demonstration crops; prior save is untouched. */}}catch{}try{const saved=JSON.parse(localStorage.getItem(SAVE)||'null');if(saved&&Array.isArray(saved.plots)&&saved.plots.length===6){state={...state,...saved};}}catch{}return state}
live=load();if(!live.stock||!live.plots)live=newState();
function save(){try{localStorage.setItem(SAVE,JSON.stringify(live));}catch{}}
function el(tag,cls,text){const out=document.createElement(tag);if(cls)out.className=cls;if(text!==undefined)out.textContent=text;return out}
function pic(name,cls,alt=''){const out=document.createElement('img');out.src=asset(name);if(cls)out.className=cls;out.alt=alt;return out}
function fit(){const mobile=window.innerWidth<800;const s=Math.min(window.innerWidth/1672,(window.innerHeight-62)/941);let scale=s;if(mobile){scale=Math.max(.51,s)}const wrap=$('scene-wrap');wrap.style.width=Math.round(1672*scale)+'px';wrap.style.height=Math.round(941*scale)+'px';$('scene').style.transform='scale('+scale+')';$('viewport').style.overflowX=1672*scale>window.innerWidth?'auto':'hidden';$('viewport').style.alignItems=mobile&&1672*scale>window.innerWidth?'flex-start':'center'}window.addEventListener('resize',fit);
function tell(message,read=false){const out=$('toast');out.textContent=message;out.classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>out.classList.remove('show'),3700);if(read&&voice&&window.speechSynthesis){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(message);u.lang='ko-KR';u.rate=.91;speechSynthesis.speak(u)}}
function step(next){action=next;document.querySelectorAll('#actions button').forEach(x=>x.classList.toggle('active',x.dataset.action===action))}
function orderFor(n){const raw=DEMO_ORDERS[n%DEMO_ORDERS.length];const price=Object.entries(raw.ask).reduce((sum,[key,count])=>sum+CROPS[key].price*count,0);return {...raw,price,reward:price+3}}
function activeOrder(){return orderFor(live.customer)}
function orderText(order){return Object.entries(order.ask).map(([k,n])=>CROPS[k].name+' '+n+'개').join(' + ')}
function planting(p){if(p.phase!=='empty')return; p.phase='seeded';p.crop=live.selected;save();render();const count=live.plots.filter(v=>v.phase==='seeded').length;tell(CROPS[p.crop].name+' 씨앗을 심었어요! 물을 주면 자라요. ('+count+'칸 새싹)',true)}
function watering(p){if(p.phase==='seeded')p.phase='growing';else if(p.phase==='growing')p.phase='ready';else{tell('씨앗을 심은 화분을 골라 주세요.');return} save();render();tell(p.phase==='ready'?'짜잔! 작물이 다 자랐어요!':'물줄기가 쪼르르! 작물이 조금 더 자랐어요.',true);celebrate(280,325,'💧')}
function harvesting(p,index){if(p.phase!=='ready'){tell('작물이 자라면 수확할 수 있어요.');return}const crop=p.crop;live.stock[crop]=(live.stock[crop]||0)+1;p.phase='empty';p.crop=null;save();render();const target=document.querySelector('#stock-tray button[data-crop="'+crop+'"]');fly(document.querySelector('.plot[data-index="'+index+'"]'),target,asset(CROPS[crop].icon));tell(CROPS[crop].name+'을 수확했어요! 창고에 1개 들어갔어요.',true)}
function pressPlot(index){const p=live.plots[index];if(!p||p.phase==='locked')return;if(action==='plant')return p.phase==='empty'?planting(p):tell('빈 화분을 터치해 주세요.');if(action==='water')return watering(p);if(action==='harvest')return harvesting(p,index);if(p.phase==='ready')return harvesting(p,index);if(p.phase==='empty')return planting(p);return watering(p)}
function renderPlots(){const root=$('farm-field');root.replaceChildren();live.plots.forEach((p,i)=>{const btn=el('button','plot');btn.type='button';btn.dataset.index=i;btn.dataset.phase=p.phase;btn.setAttribute('aria-label',(i+1)+'번 화분 '+(p.crop?CROPS[p.crop].name+' ':'')+({ready:'수확',seeded:'새싹',growing:'성장 중',empty:'빈 화분',locked:'잠김'})[p.phase]);btn.append(pic('empty_planter','plot-base',''));if(p.phase==='seeded'||p.phase==='growing'||p.phase==='ready'){const well=el('span','crop-well');let image=p.phase==='seeded'?'sprout':p.phase==='growing'?CROPS[p.crop].growth:CROPS[p.crop].plant;well.append(pic(image,'',''));btn.append(well)}btn.append(pic('empty_planter','planter-front',''));if(p.phase==='locked')btn.append(pic('lock','lock-icon',''));const label=(p.phase==='locked'?'🔒 잠김':p.phase==='empty'?'🌱 빈 화분':p.phase==='seeded'?'🌱 '+CROPS[p.crop].name:p.phase==='growing'?'💧 '+CROPS[p.crop].name:'🥬 '+CROPS[p.crop].name);const labelEl=el('span','plant-label',label);if(p.crop==='tomato'&&p.phase==='ready')labelEl.textContent='🍅 토마토';if(p.crop==='strawberry'&&p.phase==='ready')labelEl.textContent='🍓 딸기';btn.append(labelEl);if(p.phase!=='locked'){let progress=el('span','plant-progress'),fill=el('span');fill.style.width={empty:0,seeded:23,growing:60,ready:100}[p.phase]+'%';progress.append(fill);btn.append(progress)}btn.addEventListener('click',()=>pressPlot(i));root.append(btn)})}
function renderGuests(){const root=$('customers');root.replaceChildren();for(let i=0;i<3;i++){const ord=orderFor(live.customer+i),outer=el('div','guest'+(i===0?' active':'')),bubble=el('div','bubble'),row=el('div','order-icons');for(const [k,n] of Object.entries(ord.ask)){row.append(pic(CROPS[k].icon,'',CROPS[k].name),el('strong','', '×'+n))}bubble.append(row);const coin=el('div','coins');coin.append(pic('coin','', '코인'),document.createTextNode(ord.price+'코인'));const reward=el('small','',i===0?'완료 보상 '+ord.reward+'코인':'물건값 '+ord.price+'코인');coin.append(reward);bubble.append(coin);outer.append(bubble,pic(ord.guest,'',ord.guest+' 동물 손님'));const hit=el('button');hit.type='button';hit.setAttribute('aria-label',orderText(ord)+' 주문 '+(i===0?'선택됨':'대기 중'));hit.addEventListener('click',()=>tell(i===0?'첫 번째 손님의 주문은 '+orderText(ord)+'예요.':'이 동물은 잠시 기다리는 손님이에요.',true));outer.append(hit);root.append(outer)}}
function renderStock(){const root=$('stock-tray');root.replaceChildren();const needed=activeOrder().ask;for(const [key,count] of Object.entries(needed)){const b=el('button');b.type='button';b.dataset.crop=key;b.disabled=(live.stock[key]||0)<=0;b.setAttribute('aria-label',CROPS[key].name+' 1개 바구니에 담기, 창고 '+(live.stock[key]||0)+'개');b.append(pic(CROPS[key].icon,'',CROPS[key].name));b.append(el('small','',String(live.stock[key]||0)));b.addEventListener('click',()=>packOne(key,b));root.append(b)}}
function packOne(crop,source){const needed=activeOrder().ask[crop]||0,already=live.tray.filter(x=>x===crop).length;if(already>=needed){tell(CROPS[crop].name+'은 충분히 담았어요!');return}if((live.stock[crop]||0)<1){tell('먼저 '+CROPS[crop].name+'을 수확해 주세요.');return}live.stock[crop]--;live.tray.push(crop);save();renderStock();renderBasket();fly(source,$('basket-area'),asset(CROPS[crop].icon));tell(CROPS[crop].name+' 한 개가 바구니 안으로 쏙!');}
function renderBasket(){const el=$('basket-fill');el.replaceChildren();$('basket-placeholder').style.display=live.tray.length?'none':'block';const coords=[[9,26,-11],[38,8,8],[59,24,12],[25,33,-8],[49,31,10],[5,7,-13],[67,4,5],[36,16,18]];live.tray.forEach((key,i)=>{const im=pic(CROPS[key].icon,'harvest',CROPS[key].name);const [x,y,r]=coords[i%coords.length];im.style.left=x+'%';im.style.top=y+'%';im.style.transform='rotate('+r+'deg)';im.style.zIndex=String(coords.length-i);el.append(im)})}
function renderHUD(){$('coins').textContent=live.coins.toLocaleString('ko-KR');$('level').textContent='Lv. '+(Math.floor(live.served/3)+1);$('level-fill').style.width=(15+(live.served%3)*28)+'%';$('pack-title').textContent='🧺 '+orderText(activeOrder())+' 포장해요!'}
function render(){renderHUD();renderPlots();renderGuests();renderStock();renderBasket();step(action)}
function fly(from,to,src){if(!from||!to||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const scene=$('scene').getBoundingClientRect(),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),ratio=scene.width/1672;const im=document.createElement('img');im.className='fly';im.src=src;const x=(a.left+a.width/2-scene.left)/ratio-41,y=(a.top+a.height/2-scene.top)/ratio-41;im.style.left=x+'px';im.style.top=y+'px';$('scene').append(im);const dx=(b.left+b.width/2-a.left-a.width/2)/ratio,dy=(b.top+b.height/2-a.top-a.height/2)/ratio;requestAnimationFrame(()=>{im.style.transform='translate('+dx+'px,'+dy+'px) rotate(18deg) scale(.45)';im.style.opacity='.56'});setTimeout(()=>im.remove(),760)}
function celebrate(x,y,txt){const z=el('div','spark',txt);z.style.left=x+'px';z.style.top=y+'px';$('scene').append(z);setTimeout(()=>z.remove(),1300)}
function seedMenu(){const menu=$('seed-menu');menu.replaceChildren();menu.append(el('div','','어떤 씨앗을 심어 볼까요?'));for(const [key,c] of Object.entries(CROPS)){const b=el('button');b.type='button';b.append(pic(c.icon,'',c.name),el('div','',c.name));b.addEventListener('click',()=>{live.selected=key;save();menu.classList.remove('show');step('plant');tell(c.name+' 씨앗을 골랐어요! 빈 화분을 터치해요.',true)});menu.append(b)}menu.classList.add('show')}
function delivery(){const ord=activeOrder();const used={};live.tray.forEach(x=>used[x]=(used[x]||0)+1);const needed=Object.entries(ord.ask).filter(([key,n])=>(used[key]||0)<n);if(needed.length){tell('아직 '+needed.map(([k,n])=>CROPS[k].name+' '+(n-(used[k]||0))+'개').join(', ')+'가 더 필요해요.',true);step('pack');return}const menu=$('calc-menu');menu.replaceChildren();menu.classList.add('show');menu.append(el('h2','', '🧮 동물 손님 계산대'));const detail=Object.entries(ord.ask).map(([k,n])=>`${CROPS[k].name} ${n}개 × ${CROPS[k].price}코인 = ${n*CROPS[k].price}코인`).join('\n');menu.append(el('div','',detail+'\n\n물건값은 모두 몇 코인일까요?'));const btn=el('div');for(const value of [ord.price,ord.price+2,Math.max(1,ord.price-2)].sort((a,b)=>a-b)){const b=el('button','answer-btn',value+'코인');b.addEventListener('click',()=>{if(value!==ord.price)return tell('다시 한번 세어 볼까요?',true);menu.classList.remove('show');live.coins+=ord.reward;live.stars++;live.served++;live.customer++;live.day=1+Math.floor(live.served/4);live.tray=[];save();render();celebrate(1120,290,'🎊🪙⭐');tell('주문 완료! '+ord.price+'코인 물건값과 보너스 3코인, 모두 '+ord.reward+'코인을 받았어요!',true)});btn.append(b)}menu.append(btn)}
function shop(){const menu=$('shop-menu');menu.replaceChildren();menu.classList.add('show');menu.append(el('h2','', '🏡 햇살 농장 확장'));menu.append(el('p','', '기존 작물을 팔아 모은 코인으로 농장을 꾸며요.'));const open=el('button','upgrade-btn','🌱 농장 보너스 20코인');open.addEventListener('click',()=>{if(live.coins<20)return tell('코인이 더 필요해요.');live.coins-=20;live.stars+=2;save();renderHUD();tell('농장 성장 보너스 별 두 개! ⭐⭐',true);menu.classList.remove('show')});menu.append(open);const close=el('button','upgrade-btn','돌아가기');close.addEventListener('click',()=>menu.classList.remove('show'));menu.append(close)}
$('actions').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const name=b.dataset.action;step(name);if(name==='plant')return seedMenu();if(name==='water')return tell('물을 줄 새싹을 터치해요.',true);if(name==='harvest')return tell('잘 익은 작물을 터치하면 창고로 들어가요.',true);if(name==='pack')return tell('바구니 왼쪽에 있는 창고 채소를 터치해 담으세요.',true);if(name==='deliver')return delivery()});$('plus').onclick=shop;$('settings').onclick=shop;$('home').onclick=()=>{window.location.href='../../index.html'};$('sound').onclick=()=>{voice=!voice;$('sound').textContent=voice?'🔊 음성 켜짐':'🔇 음성 꺼짐';if(!voice&&window.speechSynthesis)speechSynthesis.cancel()};$('help').onclick=()=>tell('꽃밭에서 씨앗을 심고 물을 줘요. 잘 익으면 수확해 창고에 모으고, 주문한 작물만 바구니에 담은 다음 배달 버튼을 누르세요!',true);$('mode').value=live.mode||'guided';$('mode').onchange=e=>{live.mode=e.target.value;save();tell('학습 지원 설정을 저장했어요.')};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){$('seed-menu').classList.remove('show');$('shop-menu').classList.remove('show');$('calc-menu').classList.remove('show')}});
fit();render();if(live.tutorial){tell('햇살 농장에 오신 것을 환영해요! 빨갛게 익은 작물을 터치해서 수확해 보세요.');live.tutorial=false;save()}
})();
